---
- name: Configure logrotate cron job for all machines
  hosts: all
  become: yes
  tasks:
    - name: Install cron package
      apt:
        name: cron
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable cron service
      service:
        name: cron
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Create logrotate cron job - runs every 10 minutes between 2h-4h
      cron:
        name: "Logrotate job - every 10 minutes 2-4 AM"
        minute: "*/10"
        hour: "2-4"
        job: "/usr/sbin/logrotate /etc/logrotate.conf"
        user: root
        state: present
      tags:
        - cron
        - logrotate

    - name: Verify cron job was created
      shell: crontab -l | grep logrotate
      register: cron_check
      changed_when: false
      failed_when: false

    - name: Display cron job
      debug:
        msg: "Cron job created: {{ cron_check.stdout }}"
      when: cron_check.stdout != ""